/*
 * LES DESSINS EN PIXELS du menu principal, façon console 16 bits : l'icône de chaque tour (32 × 32),
 * l'écrou ⚙ des réglages (24 × 24) et la main qui montre la tuile touchée.
 *
 * Chaque dessin est une grille de caractères, un par pixel : une lettre de la palette, ou « . »
 * pour un pixel vide. src/components/PixelArt.tsx en fait un SVG de carrés, net à toutes les tailles.
 *
 * Les icônes et l'écrou sont ENGENDRÉS par outils/icones-16-bits.py (éclairage des volumes,
 * tramage des ombres, comme sur les consoles 16 bits) : pour les changer, modifier le script et
 * recopier sa sortie ici. Les tests (tests/logic/pixels.test.ts) vérifient la taille des grilles,
 * les couleurs, et que l'écrou est parfaitement symétrique, son trou au centre.
 */

/** La palette des dessins : une lettre par couleur. */
export const PALETTE: Readonly<Record<string, string>> = {
	a: '#0d0a1c',
	b: '#45258a',
	c: '#2e1863',
	d: '#1c0f3d',
	e: '#6538ad',
	f: '#d9c8f2',
	g: '#ffffff',
	h: '#0e0820',
	i: '#fff0b0',
	j: '#f2c55c',
	k: '#c98c2e',
	l: '#8f5a1c',
	m: '#5a3410',
	n: '#2a1606',
	o: '#fbf6ea',
	p: '#efe3c6',
	q: '#7a5638',
	r: '#1d2846',
	s: '#d9c69c',
	t: '#7d4c16',
	u: '#b37a26',
	v: '#4e2c0c',
	w: '#e0aa44',
	x: '#fff4c4',
	y: '#f8d778',
	z: '#160a10',
	A: '#e6dcc4',
	B: '#b13e53',
	C: '#7a1c2c',
	D: '#1c2743',
	E: '#0b0b12',
	F: '#d8e0ee',
	G: '#b0520f',
	H: '#f7931e',
	I: '#ffc46b',
	J: '#6b2a0a',
	K: '#9aa6bd',
	L: '#3a2208',
	// Le morpion : contour, papier froissé, encre bleue.
	M: '#1b2f45',
	N: '#c3d1dc',
	O: '#e6edf2',
	P: '#1d3a8a',
	// La princesse : contour, dos bleus et leur trame, cœur rouge.
	Q: '#0b1430',
	R: '#3d74c9',
	S: '#0f2a5c',
	T: '#1f4d9c',
	U: '#c8102e',
	V: '#e0646e',
	// Les trois paquets : contour vert du feutre (les cartes reprennent les blancs, le rouge et le noir).
	W: '#04230f',
	// La main : contour, blanc, ombre grise.
	1: '#0b0b12',
	2: '#ffffff',
	3: '#c6cfe0',
};

/** Taille des icônes des tours, en pixels. */
export const TAILLE = 32;

/** Taille de l'écrou, en pixels. */
export const TAILLE_ECROU = 24;

/** L'icône de chaque tour, par dossier (content/tours.ts). */
export const ICONES: Readonly<Record<string, readonly string[]>> = {
	'boule-de-cristal': [
		'................................',
		'............aaaaaaaa............',
		'..........aabbbcbccdaa..........',
		'.........abbbbbbccccdda.........',
		'........abebebbbbcbcccda........',
		'.......abefffbcbcbcbccdda.......',
		'......abefgggfbbbbbbbccdda......',
		'.....abbbggggfcbcbbbccddhha.....',
		'.....abbefgggfbbbbbbbccddha.....',
		'....abbbbfggfbcbbebbccddhhha....',
		'....acbbbbbbbcbbebebbdchhhha....',
		'....abbbcbcbcbbebebbcdhhhhha....',
		'....acbbbcbcbbebebbccddhhhha....',
		'....accbcbcccbbebbccddhhhhha....',
		'....acccccbcbbebbccddhhhhhha....',
		'....acdcdccbcbbbccddhhhhhhha....',
		'....adcdccccbbbcbcdhdhhhdhha....',
		'.....adddcdccbccddhhhhhhhha.....',
		'.....addddcccccddhhhhhhhhha.....',
		'......adhddcddddhhhhhhhhha......',
		'.......adddddddhdhhhhhhha.......',
		'........ahhhhdhhhhhhhhha........',
		'.........ahhhhhhhhhhhha.........',
		'..........aaiijjkkllaa..........',
		'..........aiiiijjkklla..........',
		'...........aaiijkklaa...........',
		'............aiijjkka............',
		'.........aaaaiiikklaaaa.........',
		'........aiiiijjkjkklllla........',
		'.......aiiiijjkjkklkllmma.......',
		'......aiiiijijjkjkklkllmla......',
		'.......aaaaaaaaaaaaaaaaaa.......',
	],
	'carte-de-visite': [
		'................................',
		'................................',
		'................................',
		'................................',
		'................................',
		'..nnnnnnnnnnnnnnnnnnnnnnnnnnn...',
		'.nooooooopopopopopopopopopoppn..',
		'nopopopopopopopopppoppppppppppn.',
		'nooqqqqqqqqqqqqqqqqqqqqqqqqqopn.',
		'nopqpopopopopopppopppppppppqppn.',
		'npoqopopoprropoprrrrrroppppqppn.',
		'nopqpopopprrpppprrrrrrpppppqspn.',
		'nooqopoprrrropopopoprrpppppqppn.',
		'nopqpoporrrrpppppppprrpppppqppn.',
		'npoqopopoprropoppprrpppppppqppn.',
		'nopqpppppprrpppppprrppppsppqspn.',
		'npoqopopoprropppoprrpppppppqppn.',
		'nopqpopppprrpppppprrppspppsqspn.',
		'npoqopoprrrrrrpppprrpppppppqpsn.',
		'nppqpppprrrrrrppsprrspspspsqspn.',
		'npoqopopoppppppppppppppppppqppn.',
		'nppqppppppppppppppspspspsijispn.',
		'npoqqqqqqqqqqqqqqqqqqqqqiiijjsn.',
		'npppppppppppspspspspspsijjsjkkn.',
		'.nppoppppppppppppppppppiispsjkn.',
		'..nnnnnnnnnnnnnnnnnnnnnijjnkkkn.',
		'......................nnjkjkkn..',
		'...................nnnjjjkkkn...',
		'................nnnjjjlllnnn....',
		'...............njjjlllnnn.......',
		'..............nklllnnn..........',
		'...............nkkn.............',
	],
	'pile-ou-face': [
		'................................',
		'................................',
		'............nnn..nnn............',
		'..........nntttnnutunn..........',
		'........nnttutututuuuunn........',
		'.......nttttttttvutuuuuun.......',
		'......nttttttttttttttuwuwn......',
		'......ntttvxwywywwwwxtuuun......',
		'.....nntttyyyyywywywywtuwnn.....',
		'....ntttvywywywywywwwwwtuwun....',
		'...nttutywywywywywywwwwwtwwwn...',
		'...nttvtwywywwwwwwwwwwwwvtwwn...',
		'..ntuttyyyxxywywywxxywwwwtwwyn..',
		'..nttuvywxttxywwwxttxwuwwtwwwn..',
		'..ntuttwytywtwywwtwwtwwwwtywyn..',
		'..nuttvywwwxtwwwwtwwtwuwutvywn..',
		'..ntutxwywxtywwwytwwtwwwwxtwyn..',
		'..nutuvywxtwwwwwwtuwtwuwutwywn..',
		'...nuutwytxxxwwwwtxxtuwwwtyyn...',
		'...ntuvwwttttwwwuwttuwuwutwyn...',
		'...nuuttywwwywwwwwwwwwwuttyyn...',
		'...nuuutwwwwwwuwwwuwuwuwvywyn...',
		'....nuwutwwwwwwwwuwwwuwtyyyn....',
		'....nuuwutwwuwuwuwuwuuvyyyyn....',
		'.....nwuwwtxwwwwwwwuxtyyyyn.....',
		'......nwwwwtvtvtvtvtvyyyyn......',
		'.......nwwwwywyttyyyyyyyn.......',
		'........nnnwwwwywywywnnn........',
		'...........nywywyyyyn...........',
		'............nnnnnnnn............',
		'................................',
		'................................',
	],
	'morpion': [
		'................................',
		'................................',
		'................MMMMMMMMMMMM....',
		'....MMMMMMMMMMMMNOOONOOONOOOM...',
		'...M22222222222OOOOOOOOOOOOOM...',
		'...MO2O2O2O2O2OOOOOOOONOOONOM...',
		'...M222222222O2OOOOOOOOOOOOOM...',
		'...MO2O2O2O2OPOONOOPNOOONOOOM...',
		'...M222222222P2OOOOPOOOOOOOOM...',
		'...MO2O2OPOPOPOOPONPOONOOONOM...',
		'...M22222OP22P2POPOPOOOOOOOOM...',
		'...MO2O2OPOPOPOOPOOPNOOONONOM...',
		'...M222222222P2OOOOPOOOOOOOOM...',
		'...MO2OPPPPPPPPPPPPPPPPPPPNOM...',
		'...M2O222O222P2OOOOPOOOOOOOOM...',
		'...MO2O2O2O2OPOPNPOPNOPONONOM...',
		'...M2222222O2P2OPOOPOPOPOOOOM...',
		'...MNONONONONPNPOPOPOOPOOOOOM...',
		'...MONONONONOPOO2O2P2O2O2O2OM...',
		'...MNONPPPPPPPPPPPPPPPPPPPOOM...',
		'...MONONONONOPOO2O2P2O2O2O2OM...',
		'...MNONONONONPNOOOOPOPOPOOOOM...',
		'...MONONONONOPOO2O2P2OPO2O2OM...',
		'...MNNNONNNONPNOOOOPOPOPOOOOM...',
		'...MONONONONOPOO2O2P2O2O2O2OM...',
		'...MNONONONNNPNOOOOPOOOOOOOOM...',
		'...MONONONONONOO2O2O2O2OOO2OM...',
		'...MNNNONNNONNNOOOOOOOOOOOOOM...',
		'...MONONONONONOOMMMMMMMMMMMM....',
		'....MMMMMMMMMMMM................',
		'................................',
		'................................',
	],
	'princesse': [
		'................................',
		'................................',
		'................................',
		'............QQQQQQQQQQQQ........',
		'...........QggggggggggggQ.......',
		'.......QQQQgRRSRRTRRSRRTgQ......',
		'......QgggggRRTRRSRRTRRTgQQQQQ..',
		'..QQQQgRRTRgSTRTSgggggggggggggQ.',
		'.QgggggRRTRgRRTRgggggggOgOgOgOgQ',
		'QgRRSRgTSRSgRRSRggUgOgOgOgOOOOgQ',
		'QgRRTRgRRSRgTSRTggUggOgOgOgOOOgQ',
		'QgSTRTgRRTRgRRSRggUUOgOgOOOOOOgQ',
		'QgRRTRgSTRTgRRTRgggggggOgOgOgOgQ',
		'QgRRSRgRRTRgSTRTggOgOgOgOgOOOOgQ',
		'QgTTRSgRRSRgRRTRgggggOgOgOgOOOgQ',
		'QgRRSRgTSRSgRRSRggOgOUUgUUOOOOgQ',
		'QgRRTRgRRSRgTSRSggggUVUUUUUOgOgQ',
		'QgSTRTgRRTRgRRSRggOgUVUUUUUOOOgQ',
		'QgRRTRgSTRTgRRTRgggggUUUUUgOOOgQ',
		'QgRRSRgRRSRgSSRTggOgOgCCCOOOOOgQ',
		'QgTSRSgRRSRgRRTRgggggggCgOgOgOgQ',
		'QgRRSRgSSRSgRRSRggOgOgOgOgOOOOgQ',
		'QgRRTRgRRSRgTSRSgggggOgOgOgOOOgQ',
		'QgSTRSgRRSRRggggggOgOgOgOOOOOOgQ',
		'QgRRTRgSTRTSRSTRgggggggOgOgOgOgQ',
		'QgRRSRRgggggggggggOgOgOgOgOOOOgQ',
		'QgTSRSTRTSRSTRgQgggggOgOgOgOOOgQ',
		'.QggggggggggggQQggOgOgOgOOOOOOgQ',
		'..QQQQQQQQQQQQ..QgggggggggggggQ.',
		'.................QQQQQQQQQQQQQ..',
		'................................',
		'................................',
	],
	'six-predictions': [
		'................................',
		'................................',
		'................................',
		'.........zzzzzzzzzzzz...........',
		'........zAAAAAAAAAAAAz..........',
		'...zzzzzAooooooooooooAz.........',
		'..zAAAAAAojBBBjBBBjBoAzzzzzzz...',
		'.zAoooooAoBjBjBjAoAoAAAAAAAAAz..',
		'.zAojBBBAoBBjBBooooAoAoAoAAAAAz.',
		'.zAoBjBjAoBjBjBoAoAoAoAAAAAAAAz.',
		'.zAoBBjBAojBBBjooAoAoAoAoAoAAAz.',
		'.zAoCjBjAoCjCjCoAoDoDDDDADDAAAz.',
		'.zAojBBBAoBBjBBooooAoAoAoAAAAAz.',
		'.zAoBjCjAoCjCjCoAoAoAoAAAAAAAAz.',
		'.zAoBBjBAojBBCjooADDDADDDAoAAAz.',
		'.zAoCjCjAoCjCjCoAoAoAAAAAAAAAAz.',
		'.zAojBBCAoBCjCBooooAoAoAoAAAAAz.',
		'.zAoCjCjAoCjCjCoAoAoAoAAAAAAAAz.',
		'.zAoBCjCAojCBCjooAoAoAoAoAoAAAz.',
		'.zAoCjCjAoCjCjCoAoAoAAAAAAAAAAz.',
		'.zAojCBCAoBCjCBooooDoDDDDADAAAz.',
		'.zAoCjCjAoCjCjCoAoAoDDDDADAAAAz.',
		'.zAoBCjCAooooooooAoAoAoAoAoAAAz.',
		'.zAoCjCjCAAAAAAoAoAoAAAAAAAAAAz.',
		'.zAooooooooooooooooAoAoAoAAAAAz.',
		'..zAAAAAAAAAAAAoAoAoAoAAAAAAAAz.',
		'...zzzzzzzzzzzzooAoAoAoAoAoAAAz.',
		'..............zoAoAoAAAAAAAAAAz.',
		'...............zoooAoAoAoAAAAz..',
		'................zzzzzzzzzzzzz...',
		'................................',
		'................................',
	],
	'cinq-cartes': [
		'................................',
		'................................',
		'................................',
		'................................',
		'................................',
		'................................',
		'....................zzzzzzzzzz..',
		'............zzzzzzzzo2o2ooooooz.',
		'.......zzzzz222o2ooz222o2o2ooooz',
		'..zzzzz2o2ozo2ooo2ozoCC2ooooooAz',
		'.z2o2oz22o2z2o2ozo2z2CCo2o2ooooz',
		'z2o2ooz2ooozo2ooz2ozoCo2ooooAoAz',
		'z22o2ozo2o2z2o2oz22z2o2o2ooooooz',
		'z2o2ooz2o2ozo2ooz2ozo2oBBoBCooAz',
		'zo2o2ozo2o2z2o2ozo2z2oBBBBCBBooz',
		'z2o2ooz2ooozooooz2ozooBBBCBBBoAz',
		'z22o2ozo2ooz2o2ozo2z2o2BCBBBoooz',
		'z2oooozoooozooooz2ozo2ooBBBoAoAz',
		'zo2ooozo2ooz2o2ozo2z2o2ooBoooAoz',
		'z2oooozoooozoooozoozooooooooAoAz',
		'zo2o2ozo2ooz2ooozo2z2o2ooooooooz',
		'z2oooozooooooooozoozooooooAoAoAz',
		'zo2ooooooooooAzzzo2z2o2ooooooAoz',
		'.zooooAoAzzzzz...zzzooooAoAoAoAz',
		'..zzzzzzz..........z2ooooooooAz.',
		'....................zzzzzzzzzz..',
		'................................',
		'................................',
		'................................',
		'................................',
		'................................',
		'................................',
	],
	'trois-paquets': [
		'................................',
		'................................',
		'................................',
		'..WWWWWWW.............WWWWWWW...',
		'.WzzzzzzzW...........WzzzzzzzW..',
		'WgUgogooooW.WWWWWWW.WgUgogooooW.',
		'WoUUgogoooWWzzzzzzzWWoUUgogoooW.',
		'WgUgooooAoWgEgooooooWgUgooooAoW.',
		'WgzzzzzzzoWgEEgogoooWgzzzzzzzoW.',
		'WgEgogooooWgEgooooAoWgEgogooooW.',
		'WoEEgogoooWozzzzzzzoWoEEgogoooW.',
		'WgEgooooAoWgUgooooooWgEgooooAoW.',
		'WgzzzzzzzoWgUUgogoooWgzzzzzzzoW.',
		'WgUgogooooWgUgooooAoWgUgogooooW.',
		'WoUUgogoooWozzzzzzzoWoUUgogoooW.',
		'WgUgooooAoWgEgooooooWgUgooooAoW.',
		'WgzzzzzzzoWgEEgogoooWgzzzzzzzoW.',
		'WgEgogooooWgEgooooAoWgEgogooooW.',
		'WoEEgogoooWozzzzzzzoWoEEgogoooW.',
		'WgEgooooAoWgUgooooooWgEgooooAoW.',
		'WggogoooooWgUUgogoooWggogoooooW.',
		'WgooooooooWgUgooooAoWgooooooooW.',
		'WogooooooAWggogoooooWogooooooAW.',
		'WgooooooAoWgooooooAoWgooooooAoW.',
		'WogogoooooWogogoooooWogogoooooW.',
		'WgooooAoAoWgogooooAoWgooooAoAoW.',
		'WogooooooAWogogooooAWogooooooAW.',
		'.WooooAoAWWgooooAoAoWWooooAoAW..',
		'..WWWWWWW.WogooooooAW.WWWWWWW...',
		'...........WooooooAW............',
		'............WWWWWWW.............',
		'................................',
	],
	'analyseur-q': [
		'................................',
		'................................',
		'................................',
		'................................',
		'................................',
		'...............EE...............',
		'..............EggE.EEEEEEE......',
		'..............EgFEEGGHGHGHEE....',
		'.............EggggGGEEEEEHIHE...',
		'............EgFgFgFE.....EEIE...',
		'..........EEgggggFgFE.....EIE...',
		'.........EJJFgFgFFFFEE....EIE...',
		'........EJgggggFgFgFFFE...EIE...',
		'.......EJgggFgFgFFFFFFKE..EIE...',
		'......EJgggggFgFgFFFFKFKEEIIE...',
		'.....EJJggFgFgFFFFFFKFKFEIHE....',
		'....EJJEgggFgFgFgFFFFFFKIIE.....',
		'...EJJEEggFgFgFFFFKFKFKIHE......',
		'...EJE..EFgFgFgFFFFFFKIHE.......',
		'...EJE...EFgFFEFKEKFKHHE........',
		'...EJE....EEEEEFFEEHIHE.........',
		'...EJE.......EFFKHHHEE..........',
		'...EJEE.....EFFHHHFE............',
		'...EJGJEEEEEGHGHKKKKE...........',
		'....EEGGGGHGHEEEEEEE............',
		'......EEEEEEE...................',
		'................................',
		'................................',
		'................................',
		'................................',
		'................................',
		'................................',
	],
};

/**
 * L'écrou ⚙ des réglages : huit dents autour d'un trou rond, au centre exact de la grille, en
 * anneaux de lumière (sombre au bord du trou, clair au milieu, dents plus sombres). Calculé pour
 * être symétrique dans tous les sens.
 */
export const ECROU: readonly string[] = [
	'........LkkkkkkL........',
	'.....LL.LkkkkkkL.LL.....',
	'....LkkLLkkkkkkLLkkL....',
	'...LkkkL.LkkkkL.LkkkL...',
	'..LkkkkkLjjjjjjLkkkkkL..',
	'.LkkkkkjjjjiijjjjkkkkkL.',
	'.LkkkkjjiiiiiiiijjkkkkL.',
	'..LLkjjiiiiiiiiiijjkLL..',
	'LLL.LjiiilllllliiijL.LLL',
	'kkkLjjiillLLLLlliijjLkkk',
	'kkkkjjiilL....Lliijjkkkk',
	'kkkkjiiilL....Lliiijkkkk',
	'kkkkjiiilL....Lliiijkkkk',
	'kkkkjjiilL....Lliijjkkkk',
	'kkkLjjiillLLLLlliijjLkkk',
	'LLL.LjiiilllllliiijL.LLL',
	'..LLkjjiiiiiiiiiijjkLL..',
	'.LkkkkjjiiiiiiiijjkkkkL.',
	'.LkkkkkjjjjiijjjjkkkkkL.',
	'..LkkkkkLjjjjjjLkkkkkL..',
	'...LkkkL.LkkkkL.LkkkL...',
	'....LkkLLkkkkkkLLkkL....',
	'.....LL.LkkkkkkL.LL.....',
	'........LkkkkkkL........',
];

/** La main des menus de jeux de rôle 16 bits, qui montre la tuile touchée. */
export const MAIN: readonly string[] = [
	'................',
	'...11111........',
	'..1222221111111.',
	'..12222222222221',
	'..1222221111111.',
	'.132222221......',
	'.1322222221.....',
	'.133222221......',
	'..13332221......',
	'...1133321......',
	'.....1111.......',
	'................',
];
